# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run iOS tests
      run: xcodebuild test -scheme SimilaritySearchKit-Package -destination "platform=iOS Simulator,name=$(xcrun simctl list devices available 'iOS' | grep -o 'iPhone.*' | tail -n 1)"
    - name: Run macOS tests
      run: xcodebuild test -scheme SimilaritySearchKit-Package -destination 'generic/platform=macOS,arch=arm64,name=Any Mac'
